# Generated by Django 5.2.11 on 2026-03-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='rfq_file',
            field=models.FileField(upload_to='uploads/rfq/'),
        ),
    ]
