# Generated by Django 6.0.2 on 2026-03-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='rfq_file',
            field=models.FileField(default=1, upload_to='uploads/rfq/'),
            preserve_default=False,
        ),
    ]
