# Generated by Django 5.2.13 on 2026-04-07 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('temp', 'Temporary Category')], max_length=50)),
                ('min_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_budget', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quotation', models.FileField(upload_to='uploads/quotations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
                ('consumer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='marketplace.consumerrequest')),
            ],
            options={
                'db_table': 'business_response',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('temp', 'Temporary Category')], max_length=50)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit', models.CharField(max_length=10)),
                ('delivery_option', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery'), ('shipping', 'Shipping')], max_length=10)),
                ('delivery_time', models.IntegerField()),
                ('terms_conditions', models.FileField(upload_to='uploads/listings/termsconditions')),
                ('availability', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/listings/images/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.listing')),
            ],
        ),
    ]
