# Generated by Django 5.2.13 on 2026-04-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='delivery_area',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
