# Generated by Django 5.2.13 on 2026-04-12 07:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_listing_delivery_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumerrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='consumerrequest',
            name='contact_pref',
            field=models.CharField(default='Phone', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumerrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumerrequest',
            name='delivery_area',
            field=models.CharField(default='Quezon City', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumerrequest',
            name='needed_by',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumerrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='consumerrequest',
            table='request',
        ),
        migrations.CreateModel(
            name='RequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/requests/images/')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.consumerrequest')),
            ],
        ),
    ]
