# Generated by Django 5.2.13 on 2026-04-12 10:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_consumerrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessresponse',
            name='earliest_delivery',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessresponse',
            name='latest_delivery',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
