# Generated by Django 5.2.13 on 2026-04-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_businessresponse_earliest_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerrequest',
            name='status',
            field=models.CharField(choices=[('none', 'No Responses'), ('response', 'Received Responses'), ('closed', 'Closed')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='consumerrequest',
            name='contact_pref',
            field=models.CharField(choices=[('message', 'Message'), ('email', 'Email'), ('phone', 'Phone')], max_length=10),
        ),
    ]
