# Generated by Django 5.1.6 on 2026-04-18 01:55

import django.db.models.deletion
import marketplace.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_consumerrequest_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerrequest',
            name='max_budget',
        ),
        migrations.RemoveField(
            model_name='consumerrequest',
            name='min_budget',
        ),
        migrations.AddField(
            model_name='consumerrequest',
            name='consumer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_request', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumerrequest',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, validators=[marketplace.models.validate_nonnegative]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumerrequest',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, validators=[marketplace.models.validate_nonnegative]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumerrequest',
            name='response_count',
            field=models.IntegerField(default=0, validators=[marketplace.models.validate_nonnegative]),
        ),
        migrations.AddField(
            model_name='listing',
            name='quantity',
            field=models.IntegerField(default=1, validators=[marketplace.models.validate_nonnegative]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='view_count',
            field=models.IntegerField(default=0, validators=[marketplace.models.validate_nonnegative]),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='order',
            field=models.IntegerField(default=1, validators=[marketplace.models.validate_nonnegative]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessresponse',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[marketplace.models.validate_nonnegative]),
        ),
        migrations.AlterField(
            model_name='consumerrequest',
            name='category',
            field=models.CharField(choices=[('goods', 'Goods'), ('services', 'Services'), ('custom', 'Custom')], default='custom', max_length=50),
        ),
        migrations.AlterField(
            model_name='consumerrequest',
            name='contact_pref',
            field=models.CharField(blank=True, choices=[('message', 'Message'), ('email', 'Email'), ('phone', 'Phone')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='consumerrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('goods', 'Goods'), ('services', 'Services'), ('custom', 'Custom')], default='custom', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='max_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[marketplace.models.validate_nonnegative]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='min_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[marketplace.models.validate_nonnegative]),
        ),
        migrations.AlterModelTable(
            name='consumerrequest',
            table='consumer_request',
        ),
        migrations.CreateModel(
            name='ConsumerRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/consumer_requests/images/')),
                ('consumer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.consumerrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerRequestTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, validators=[marketplace.models.validate_nonnegative])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_request_transaction', to='marketplace.businessresponse')),
                ('consumer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_request_transaction', to='marketplace.consumerrequest')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_favorite_date', models.DateTimeField(auto_now_add=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_listing', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_listing', to='marketplace.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, validators=[marketplace.models.validate_nonnegative])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_transaction', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_transaction', to='marketplace.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.IntegerField(validators=[marketplace.models.validate_rating])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumer_request_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='marketplace.consumerrequesttransaction')),
                ('listing_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='marketplace.listingtransaction')),
            ],
        ),
        migrations.DeleteModel(
            name='RequestImage',
        ),
    ]
