# Generated by Django 5.1.6 (manually fixed — transaction_ptr default corrected)

import django.db.models.deletion
import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_remove_consumerrequest_max_budget_and_more'),
    ]

    operations = [
        # 1. Create the new base Transaction table
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, validators=[marketplace.models.validate_nonnegative])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(max_length=1)),
            ],
        ),

        # 2. Strip the fields that are moving up to the Transaction table
        migrations.RemoveField(
            model_name='consumerrequesttransaction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='consumerrequesttransaction',
            name='id',
        ),
        migrations.RemoveField(
            model_name='consumerrequesttransaction',
            name='price',
        ),
        migrations.RemoveField(
            model_name='listingtransaction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='listingtransaction',
            name='id',
        ),
        migrations.RemoveField(
            model_name='listingtransaction',
            name='price',
        ),

        # 3. Remove old Review FKs
        migrations.RemoveField(
            model_name='review',
            name='consumer_request_transaction',
        ),
        migrations.RemoveField(
            model_name='review',
            name='listing_transaction',
        ),

        # 4. Add parent link to ConsumerRequestTransaction
        #    default=1 is a placeholder — DB is empty so it will never be used
        migrations.AddField(
            model_name='consumerrequesttransaction',
            name='transaction_ptr',
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to='marketplace.transaction',
            ),
            preserve_default=False,
        ),

        # 5. Add parent link to ListingTransaction
        migrations.AddField(
            model_name='listingtransaction',
            name='transaction_ptr',
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to='marketplace.transaction',
            ),
            preserve_default=False,
        ),

        # 6. Add new single-FK Review.transaction
        migrations.AddField(
            model_name='review',
            name='transaction',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='review',
                to='marketplace.transaction',
            ),
        ),
    ]
