# Generated by Django 6.0.2 on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_businessprofile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/profile_pictures/'),
        ),
    ]
