# Generated by Django 5.1.6 on 2026-04-25 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_client_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
